
#line 2 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 85
#define YY_END_OF_BUFFER 86
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[236] =
    {   0,
       82,   82,    0,    0,    0,    0,   86,   84,   82,   83,
       70,   84,   55,   56,   32,   54,   59,   58,   43,   43,
       61,   57,   53,   60,   53,   35,   35,   35,   35,   35,
       35,   35,   35,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   62,   63,   84,   66,   67,   68,   69,   81,
       72,   71,   85,   82,    0,    0,    0,    0,    0,   65,
       38,   38,    0,    0,    0,    0,   43,   64,   53,   35,
       35,   35,    0,   35,   35,   35,   35,   35,   22,   35,
       35,   35,   35,   35,   18,   34,   35,   35,    6,   31,
       35,   35,   35,   35,   25,   35,   35,   35,   35,   35,

       35,   35,   67,   81,   80,   79,   76,   78,   73,   75,
       74,   77,   50,   52,   51,    0,    0,    0,    0,    0,
        0,   50,    0,    0,   38,    0,    0,   42,    0,   39,
       39,    0,   41,   32,   35,   35,   35,   35,   35,   32,
       35,   35,   17,   35,   23,   35,   35,   32,   33,   35,
       35,   35,    5,   35,   35,   35,    8,   35,   35,   35,
       48,   46,   44,   47,   45,   49,    0,   40,   40,   37,
       37,   42,   39,   36,   36,   41,   35,   35,   35,   15,
       35,   35,   20,   35,   35,   35,   35,   35,   35,   27,
       13,   35,   19,   29,    3,   35,   26,   35,   40,    0,

       37,    0,   36,    4,   16,   35,    2,   35,   30,   35,
       35,   35,   35,   35,   35,   21,   28,   35,   24,   35,
       35,   35,   35,   35,    7,   14,    9,   35,   12,   35,
        1,   10,   35,   11,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    5,    5,    5,    5,    7,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,    5,    5,   24,   25,   26,   27,   28,   29,
       30,   31,   32,   33,   33,   34,   35,   36,   37,   38,
       33,   39,   40,   41,   42,   43,   44,   33,   45,   33,
       46,   47,   48,    5,   49,    5,   50,   51,   52,   53,

       54,   55,   56,   57,   58,   33,   33,   59,   60,   61,
       62,   63,   33,   64,   65,   66,   67,   68,   69,   33,
       70,   33,   71,    5,   72,    5,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[73] =
    {   0,
        1,    1,    2,    3,    3,    4,    3,    3,    3,    3,
        1,    3,    3,    5,    3,    6,    7,    7,    3,    3,
        3,    3,    3,    8,    8,    8,    8,    8,    8,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    3,    4,    3,   10,    8,
        8,    8,    8,    8,    8,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        3,   11
    } ;

static const flex_int16_t yy_base[248] =
    {   0,
        0,    0,   70,   71,   72,   73,  595,  686,   78,  686,
      686,  140,  686,  686,  686,  686,  686,   67,   72,   73,
      572,  686,  570,  686,  569,   57,   76,   79,   75,  131,
      154,  541,  145,  102,  133,  144,   53,   60,  148,  170,
      174,  186,  686,  686,    0,  686,    0,  686,  686,    0,
      686,  686,  248,  130,  582,  581,  580,  292,  579,  686,
      213,  220,  229,  152,  241,  571,  247,  686,  686,  535,
      229,  221,  533,  223,  177,  231,  247,  243,  244,  255,
      241,  266,  258,  269,  530,  257,  283,  278,  528,  527,
      289,  313,  293,  156,  501,   73,  291,  306,  292,  308,

      320,  500,    0,    0,  686,  686,  686,  686,  686,  686,
      686,  686,  686,  686,  686,  532,  527,  492,  482,  480,
      475,  686,  350,  364,  355,   78,  451,  370,  372,  686,
      375,  442,  436,  399,  352,  347,  351,  355,  357,  382,
      359,  375,  368,  358,  367,  386,  385,  366,  350,  388,
      394,  393,  315,  396,  397,  405,  312,  407,  418,  411,
      686,  686,  686,  686,  686,  686,  445,  686,  452,   82,
      155,  457,  462,  332,    0,  332,  427,  445,  436,  253,
      442,  443,  227,  458,  464,  452,  466,  467,  461,  222,
      220,  478,  217,  213,  200,  470,  193,  474,  487,  410,

      513,  217,    0,  179,  173,  487,  171,  483,  164,  492,
      494,  505,  508,  514,  513,  136,  130,  511,  128,  521,
      509,  516,  502,  518,  126,   86,   82,  532,   62,  534,
       59,   56,  547,   28,  686,  601,  612,  621,  627,  630,
      639,  649,  660,  667,  670,  674,  677
    } ;

static const flex_int16_t yy_def[248] =
    {   0,
      235,    1,  236,  236,  237,  237,  235,  235,  235,  235,
      235,  238,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  235,  235,  240,  235,  241,  235,  235,  242,
      235,  235,  243,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  244,  235,  235,  235,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,

      239,  239,  241,  242,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  245,  246,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  245,  247,  246,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  235,  235,

      235,  245,  247,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,  239,  239,  239,  239,  239,  239,
      239,  239,  239,  239,    0,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235
    } ;

static const flex_int16_t yy_nxt[759] =
    {   0,
        8,    9,   10,    9,    8,   11,   12,   13,   14,   15,
       16,   17,   16,   18,   15,   19,   20,   20,   21,   22,
       23,   24,   25,   26,   27,   28,   29,   30,   31,   32,
       32,   33,   32,   32,   34,   35,   36,   37,   38,   39,
       40,   32,   41,   42,   32,   43,    8,   44,   45,   26,
       27,   28,   29,   30,   31,   32,   32,   33,   32,   34,
       35,   36,   37,   38,   39,   40,   32,   41,   42,   32,
       46,    8,   48,   48,   51,   51,   73,   52,   52,   54,
       60,   54,   61,   62,   62,   63,   63,   92,   67,   67,
       67,   91,   71,  170,  171,   72,   64,  200,  171,   65,

       65,   73,   66,   74,   73,   73,   78,   73,   73,   76,
       73,   79,   75,   92,  155,   77,   91,   71,   53,   53,
       72,   73,   64,   73,   73,   65,   65,   73,   66,   74,
       73,   54,   78,   54,   73,   76,   79,   75,   87,  155,
       77,   49,   49,   55,   55,   55,   55,   55,   55,   55,
       73,   55,   55,   55,   55,   56,   56,   56,   55,   55,
       55,   55,   55,   87,   80,  126,   81,  127,  128,   88,
      201,  201,   89,   85,   73,   93,   73,   82,   73,   73,
       86,   73,   90,  154,   73,   55,   58,   55,   59,   80,
       83,   81,   73,   73,   88,   84,   73,   98,   89,   85,

       94,   93,   73,   82,   73,   86,   95,   90,   96,  154,
       55,   55,   73,  137,   97,   83,   99,  100,   73,   73,
       84,   73,   73,   98,  101,   73,   94,   73,  123,   62,
       62,   95,  202,   96,   73,  125,  125,  125,  137,   97,
      124,   73,   99,  100,   61,   62,   62,  124,   73,  101,
      106,  129,  136,  129,  138,  134,  130,  131,  131,  135,
       63,   73,   67,   67,   67,   73,  124,  143,   73,   73,
       73,   73,  107,  124,   65,   73,  108,   73,  136,   73,
      138,  134,  139,  109,  135,  140,  110,  141,  111,   73,
      112,   73,   73,  143,  142,   73,  145,  147,  107,  144,

       65,   73,  108,   73,  146,   73,   73,  139,  109,  148,
      140,  110,  141,  111,   73,  112,  116,   73,  149,  142,
      117,  145,  147,  158,  144,  150,   73,  118,  156,  146,
      119,   73,  120,  153,  121,  148,  151,   73,  152,   73,
       73,   73,  116,  149,  157,  132,  117,  202,  159,  158,
      150,  160,  118,  156,   73,  119,   73,  120,  153,  121,
       73,   73,  151,   73,  152,  123,   62,   62,   73,  157,
      125,  125,  125,  159,  167,  177,  167,  160,  178,  168,
      169,  169,  124,  126,  179,  172,  172,  130,  131,  131,
      173,  173,  173,  180,  182,   73,  181,  184,   73,   73,

       73,  177,  183,   73,  178,   73,   73,   73,  124,  179,
      185,  186,  187,  188,   73,   73,   73,  189,  180,  182,
      190,  181,  184,   73,  194,  200,  171,  191,  183,  192,
       73,  193,  195,   73,   73,  185,   73,  186,  187,  188,
      196,   73,   73,  189,   73,   73,  190,   73,  197,  132,
      194,  198,  191,   73,  192,   73,  193,  174,  195,   73,
      168,  169,  169,  206,  126,  196,   73,  199,  199,  199,
      126,  204,  172,  172,  197,   73,  198,  173,  173,  173,
      205,  166,  207,  208,   73,  209,  165,  210,  164,  206,
       73,   73,  211,   73,  213,  212,  204,  216,  163,  214,

       73,  217,  199,  199,  199,  205,   73,  207,  208,   73,
      218,  209,   73,  210,   73,   73,  215,  211,   73,  219,
      213,  212,   73,  216,  214,  221,   73,  217,  201,  201,
      220,   73,  222,  162,  223,   73,  218,  224,  161,  225,
       73,  215,   73,  230,  219,  228,  226,  227,   73,   73,
       73,  221,  231,   73,  229,  220,   73,   73,  222,   73,
      223,   73,   73,  224,   73,  225,   73,  232,  230,   73,
      228,  226,  233,  227,  234,   73,   73,  231,   73,  229,
       73,   73,   73,   73,  132,  122,  115,  114,  113,   73,
       69,   69,  232,   68,  235,   73,  235,  233,  235,  235,

      234,   47,   47,   47,   47,   47,   47,   47,   47,   47,
       47,   47,   50,   50,   50,   50,   50,   50,   50,   50,
       50,   50,   50,   57,   57,   57,   57,   57,   57,   57,
       57,   57,   70,   70,   70,   70,   70,  102,  102,  103,
      235,  103,  103,  103,  103,  103,  103,  103,  103,  104,
      235,  104,  235,  104,  104,  104,  104,  104,  104,  104,
      105,  105,  105,  105,  105,  105,  105,  105,  105,  105,
      105,  133,  235,  133,  133,  175,  175,  175,  176,  176,
      176,  176,  203,  203,  203,    7,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235
    } ;

static const flex_int16_t yy_chk[759] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    3,    4,    5,    6,  234,    5,    6,    9,
       18,    9,   18,   18,   18,   19,   20,   38,   20,   20,
       20,   37,   26,  126,  126,   26,   19,  170,  170,   19,

       20,   37,   19,   27,  232,   26,   29,  231,   38,   28,
      229,   29,   27,   38,   96,   28,   37,   26,    5,    6,
       26,   96,   19,   29,   27,   19,   20,   28,   19,   27,
      227,   54,   29,   54,  226,   28,   29,   27,   34,   96,
       28,    3,    4,   12,   12,   12,   12,   12,   12,   12,
       34,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   34,   30,   64,   30,   64,   64,   35,
      171,  171,   36,   33,  225,   39,  219,   31,  217,   30,
       33,   35,   36,   94,  216,   12,   12,   12,   12,   30,
       31,   30,   36,   33,   35,   31,   39,   41,   36,   33,

       40,   39,   31,   31,   94,   33,   40,   36,   40,   94,
       12,   12,  209,   75,   40,   31,   42,   42,   40,  207,
       31,  205,   41,   41,   42,   75,   40,  204,   61,   61,
       61,   40,  202,   40,   42,   62,   62,   62,   75,   40,
       61,  197,   42,   42,   63,   63,   63,   62,  195,   42,
       53,   65,   74,   65,   76,   71,   65,   65,   65,   72,
       67,  194,   67,   67,   67,  193,   61,   81,  191,   72,
      190,   74,   53,   62,   67,  183,   53,   71,   74,   76,
       76,   71,   77,   53,   72,   78,   53,   79,   53,   81,
       53,   78,   79,   81,   80,   77,   83,   86,   53,   82,

       67,  180,   53,   80,   84,   86,   83,   77,   53,   87,
       78,   53,   79,   53,   82,   53,   58,   84,   88,   80,
       58,   83,   86,   99,   82,   91,   88,   58,   97,   84,
       58,   87,   58,   93,   58,   87,   92,   91,   92,   97,
       99,   93,   58,   88,   98,  176,   58,  174,  100,   99,
       91,  101,   58,   97,   98,   58,  100,   58,   93,   58,
      157,   92,   92,  153,   92,  123,  123,  123,  101,   98,
      125,  125,  125,  100,  124,  135,  124,  101,  136,  124,
      124,  124,  125,  128,  137,  128,  128,  129,  129,  129,
      131,  131,  131,  138,  141,  136,  139,  144,  149,  137,

      135,  135,  142,  138,  136,  139,  144,  141,  125,  137,
      145,  146,  147,  150,  148,  145,  143,  150,  138,  141,
      151,  139,  144,  142,  155,  200,  200,  151,  142,  152,
      140,  154,  156,  147,  146,  145,  150,  146,  147,  150,
      158,  152,  151,  150,  154,  155,  151,  134,  159,  133,
      155,  160,  151,  156,  152,  158,  154,  132,  156,  160,
      167,  167,  167,  179,  127,  158,  159,  169,  169,  169,
      172,  177,  172,  172,  159,  177,  160,  173,  173,  173,
      178,  121,  181,  182,  179,  184,  120,  185,  119,  179,
      181,  182,  186,  178,  188,  187,  177,  196,  118,  189,

      186,  198,  199,  199,  199,  178,  184,  181,  182,  189,
      206,  184,  185,  185,  187,  188,  192,  186,  196,  208,
      188,  187,  198,  196,  189,  211,  192,  198,  201,  201,
      210,  208,  212,  117,  213,  206,  206,  214,  116,  215,
      210,  192,  211,  223,  208,  221,  218,  220,  102,   95,
      223,  211,  224,  212,  222,  210,  213,  221,  212,  218,
      213,  215,  214,  214,  222,  215,  224,  228,  223,  220,
      221,  218,  230,  220,  233,   90,   89,  224,   85,  222,
      228,   73,  230,   70,   66,   59,   57,   56,   55,   32,
       25,   23,  228,   21,    7,  233,    0,  230,    0,    0,

      233,  236,  236,  236,  236,  236,  236,  236,  236,  236,
      236,  236,  237,  237,  237,  237,  237,  237,  237,  237,
      237,  237,  237,  238,  238,  238,  238,  238,  238,  238,
      238,  238,  239,  239,  239,  239,  239,  240,  240,  241,
        0,  241,  241,  241,  241,  241,  241,  241,  241,  242,
        0,  242,    0,  242,  242,  242,  242,  242,  242,  242,
      243,  243,  243,  243,  243,  243,  243,  243,  243,  243,
      243,  244,    0,  244,  244,  245,  245,  245,  246,  246,
      246,  246,  247,  247,  247,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,

      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235,  235,  235,
      235,  235,  235,  235,  235,  235,  235,  235
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "compilers.l"
/*Homework 1 Compilers/ 27/11/2015
Christodoulou Vasilis 1834
Kostakis Nikos 1775
Papadopoulou Chryssa 1743
Papadopoulou Iliana 1742*/
/*LEXICAL ANALYSIS of PASCAL320
As far as error correction is concerned, parsing stops when errors take the value of MAX_ERRORS. Each time a character , which cannot
be considered as a token, is found is erased from parsing and the parser continues with the next token.
yyterminate() terminates the scanner and returns a 0 to the scanner's caller, indicating “all done”. 
By default, yyterminate() is also called when an end-of-file is encountered.*/ 
#line 14 "compilers.l"
#include <sys/types.h>
#include <unistd.h>
#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "compilers.h"

/*Pointer we use to access the file and store the line which we found an error*/
FILE *yyin1;
/*Flag = 0 when yyin1 find eof. Flag = 1 otherwise*/
int flag = 1;
/*error_count :# of errors encountered in flex*/
int error_count = 0;
/*lineno: # of lines in the program*/
int lineno = 1;
char linestream[MAX_LINE_SIZE];
/*in string_buf we store the strings encountered in the program*/ 
char string_buf[MAX_STR_CONST];
char *string_buf_ptr;


/*Function with which we store the line every time we find a new line character*/
void error_string(void);

/*Print error messages when errors found in code*/
void yyerror(char *message);

/*Functions that return the literal values in decimal format istead of a string one*/
int decIntHandle(char *str);
int hexIntHandle(char *str);
int binIntHandle(char *str);

/*Functions that return the literal values in real format istead of a string one*/
double decRealHandle(char *str);
double hexRealHandle(char *str);
double binRealHandle(char *str);
#line 739 "lex.yy.c"
/*option noyywrap:makes the scanner not call yywrap() upon an end-of-file, but simply assume that there are no more files to scan (until the user points yyin at a new file and calls yylex() again)*/
/*option case-insensitive:the case of letters given in the flex input.Patterns will be ignored  and tokens in the input will be matched regardless of case*/
/*State of comments*/
 
/*State of strings*/

/*UNSINT:unsigned integer */
#line 747 "lex.yy.c"

#define INITIAL 0
#define COMMENT 1
#define STRING 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 75 "compilers.l"


#line 78 "compilers.l"
 /* KEYWORDS */
#line 971 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 236 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 686 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 79 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_PROGRAM, lineno); 
																	return T_PROGRAM;}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 81 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CONST, lineno); 
																	return T_CONST;}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 83 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_TYPE, lineno);
																	return T_TYPE;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 85 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_ARRAY, lineno); 
																	return T_ARRAY;}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 87 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_SET, lineno); 
																	return T_SET;}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 89 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_OF, lineno); 
																	return T_OF;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 91 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_RECORD, lineno); 
																	return T_RECORD;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 93 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_VAR, lineno); 
																	return T_VAR;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 95 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_FORWARD, lineno); 
																	return T_FORWARD;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 97 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_FUNCTION, lineno); 
																	return T_FUNCTION;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 99 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_PROCEDURE, lineno); 
																	return T_PROCEDURE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 101 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_INTEGER, lineno); 
																	return T_INTEGER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 103 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_REAL, lineno); 
																	return T_REAL;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 105 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_BOOLEAN, lineno); 
																	return T_BOOLEAN;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 107 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CHAR, lineno); 
																	return T_CHAR;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 109 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_BEGIN, lineno); 
																	return T_BEGIN;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 111 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_END, lineno); 
																	return T_END;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 113 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_IF, lineno); 
																	return T_IF;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 115 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_THEN, lineno); 
																	return T_THEN;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 117 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_ELSE, lineno); 
																	return T_ELSE;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 119 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_WHILE, lineno); 
																	return T_WHILE;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 121 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_DO, lineno); 
																	return T_DO;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 123 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_FOR, lineno); 
																	return T_FOR;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 125 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_DOWNTO, lineno); 
																	return T_DOWNTO;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 127 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_TO, lineno); 
																	return T_TO;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 129 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_WITH, lineno); 
																	return T_WITH;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 131 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_READ, lineno); 
																	return T_READ;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 133 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_WRITE, lineno); 
																	return T_WRITE;}
	YY_BREAK
/* BOOLEAN KEYWORDS */
case 29:
YY_RULE_SETUP
#line 138 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_BCONST, lineno); 
																	return T_BCONST;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 140 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_BCONST, lineno); 
																	return T_BCONST;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 142 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_OROP, lineno); 
																	return T_OROP;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 144 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_MULDIVANDOP, lineno); 
																	return T_MULDIVANDOP;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 146 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_NOTOP, lineno); 
																	return T_NOTOP;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 148 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_INOP, lineno); 
																	return T_INOP;}
	YY_BREAK
/* IDENTIFIER */
case 35:
YY_RULE_SETUP
#line 153 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_ID, lineno); 
																	return T_ID;}
	YY_BREAK
/* REAL HEXADEMICAL CONSTANT */
case 36:
YY_RULE_SETUP
#line 158 "compilers.l"
{printf("[TOKEN FOUND: %s = %lf | TOKEN NUMBER: %d | LINE: %d]\n",
																	yytext, hexRealHandle(yytext), T_RHEXCONST, lineno); return T_RHEXCONST;}
	YY_BREAK
/* REAL BINARY CONSTANT */
case 37:
YY_RULE_SETUP
#line 161 "compilers.l"
{printf("[TOKEN FOUND: %s = %lf | TOKEN NUMBER: %d | LINE: %d]\n",
																	yytext, binRealHandle(yytext), T_RBINCONST, lineno); return T_RBINCONST;} 
	YY_BREAK
/* REAL DECIMAL CONSTANT */
case 38:
YY_RULE_SETUP
#line 165 "compilers.l"
{printf("[TOKEN FOUND: %s = %lf | TOKEN NUMBER: %d | LINE: %d]\n",
																	yytext, decRealHandle(yytext), T_RDECCONST, lineno); return T_RDECCONST;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 168 "compilers.l"
{printf("[TOKEN FOUND: %s = %lf | TOKEN NUMBER: %d | LINE: %d]\n",
																	yytext, decRealHandle(yytext), T_RDECCONST, lineno); return T_RDECCONST;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 171 "compilers.l"
{printf("[TOKEN FOUND: %s = %lf | TOKEN NUMBER: %d | LINE: %d]\n",
																	yytext, decRealHandle(yytext), T_RDECCONST, lineno); return T_RDECCONST;}
	YY_BREAK
/* HEXADEMICAL CONSTANT */
case 41:
YY_RULE_SETUP
#line 176 "compilers.l"
{printf("[TOKEN FOUND: %s = %d | TOKEN NUMBER: %d | LINE: %d]\n", 
																	yytext, hexIntHandle(yytext), T_HEXCONST, lineno); return T_HEXCONST;}
	YY_BREAK
/* BINARY CONSTANT */
case 42:
YY_RULE_SETUP
#line 179 "compilers.l"
{printf("[TOKEN FOUND: %s = %d | TOKEN NUMBER: %d | LINE: %d]\n", 
																	yytext, binIntHandle(yytext), T_BINCONST, lineno); return T_BINCONST;}																	
	YY_BREAK
/* INTEGER CONSTANT */
case 43:
YY_RULE_SETUP
#line 182 "compilers.l"
{printf("[TOKEN FOUND: %s = %d | TOKEN NUMBER: %d | LINE: %d]\n", 
																	yytext, decIntHandle(yytext), T_DECCONST, lineno); return T_DECCONST;}
	YY_BREAK
/* CCONST */
case 44:
YY_RULE_SETUP
#line 186 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 188 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 190 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 192 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 194 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 196 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																return T_CCONST;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 198 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 200 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 202 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_CCONST, lineno); 
																	return T_CCONST;}
	YY_BREAK
/*Operators*/																
case 53:
YY_RULE_SETUP
#line 207 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_RELOP, lineno); 
																	return T_RELOP;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 209 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_ADDOP, lineno); 
																	return T_ADDOP;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 213 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_LPAREN, lineno); 
																	return T_LPAREN;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 215 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_RPAREN, lineno); 
																	return T_RPAREN;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 217 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_SEMI, lineno); 
																	return T_SEMI;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 219 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_DOT, lineno); 
																	return T_DOT;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 221 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_COMMA, lineno); 
																	return T_COMMA;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 223 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_EQU, lineno); 
																	return T_EQU;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 225 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_COLON, lineno); 
																	return T_COLON;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 227 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_LBRACK, lineno); 
																	return T_LBRACK;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 229 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_RBRACK, lineno); 
																	return T_RBRACK;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 231 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_ASSIGN, lineno); 
																	return T_ASSIGN;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 233 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_DOTDOT, lineno); 
																	return T_DOTDOT;}
	YY_BREAK
case YY_STATE_EOF(INITIAL):
#line 235 "compilers.l"
{printf("[TOKEN FOUND: %s | TOKEN NUMBER: %d | LINE: %d]\n", yytext, T_EOF, lineno); 
																	return T_EOF;}
	YY_BREAK
/* Comments */
case 66:
YY_RULE_SETUP
#line 240 "compilers.l"
BEGIN(COMMENT);
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 241 "compilers.l"
;
	YY_BREAK
case 68:
/* rule 68 can match eol */
YY_RULE_SETUP
#line 242 "compilers.l"
{if(flag) error_string(); lineno++;}
	YY_BREAK
case YY_STATE_EOF(COMMENT):
#line 243 "compilers.l"
{yyerror("Unterminated comment"); yyterminate();}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 244 "compilers.l"
BEGIN(INITIAL);
	YY_BREAK
/* Strings */ 
case 70:
YY_RULE_SETUP
#line 248 "compilers.l"
{string_buf_ptr = string_buf; BEGIN(STRING);}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 249 "compilers.l"
{BEGIN(INITIAL); *string_buf_ptr = '\0';
																printf("[STRING FOUND: \"%s\" | TOKEN NUMBER: %d | LINE: %d]\n" ,string_buf, T_STRING, lineno);}
	YY_BREAK
case 72:
/* rule 72 can match eol */
YY_RULE_SETUP
#line 252 "compilers.l"
yyerror("Illegal input in string");
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 253 "compilers.l"
*string_buf_ptr++ = '\n';
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 254 "compilers.l"
*string_buf_ptr++ = '\t';
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 255 "compilers.l"
*string_buf_ptr++ = '\r';
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 256 "compilers.l"
*string_buf_ptr++ = '\b';
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 257 "compilers.l"
*string_buf_ptr++ = '\v';
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 258 "compilers.l"
*string_buf_ptr++ = '\f';
	YY_BREAK
case 79:
/* rule 79 can match eol */
YY_RULE_SETUP
#line 259 "compilers.l"
{if(flag) error_string(); lineno++;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 260 "compilers.l"
*string_buf_ptr++ = yytext[1];
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 261 "compilers.l"
{char *yptr = yytext; 
																while ( *yptr ){ *string_buf_ptr++ = *yptr++;}}
	YY_BREAK
case YY_STATE_EOF(STRING):
#line 263 "compilers.l"
{yyerror("Unterminated string"); yyterminate();}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 266 "compilers.l"
;
	YY_BREAK
case 83:
/* rule 83 can match eol */
YY_RULE_SETUP
#line 267 "compilers.l"
{if(flag) error_string(); lineno++;} 
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 270 "compilers.l"
yyerror("Illegal input");
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 273 "compilers.l"
ECHO;
	YY_BREAK
#line 1549 "lex.yy.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 236 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 236 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 235);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 273 "compilers.l"



int decIntHandle(char *str){
    return atoi(str);
}

int hexIntHandle(char *str){
    int res;
    res = (int)strtol(&str[2], NULL, 16);
    return res;
}

int binIntHandle(char *str){
    int res;
    res = (int)strtol(&str[2], NULL, 2);
    return res;
}

double decRealHandle(char *str){
	return atof(str);
}

double hexRealHandle(char *str){
    double res;
    int i;
    int length_str, length_decimal, length_real;
    char *character;
    
    length_str = strlen(str);
    character = strchr(str, '.');
    length_real = strlen(character) - 1;
    length_decimal = length_str - length_real + 1;
    
    res = (int)strtol(&str[2], &character, 16);
    
    for (i = 1; i <= length_real; i++){
		if ((character[i] == 'A') || (character[i] == 'B') || (character[i] == 'C') || (character[i] == 'D') || (character[i] == 'E') || (character[i] == 'F')){
			res = (character[i] - '7') * (1 / pow(16,i)) + res;
		}else{
			if ((character[i] == 'a') || (character[i] == 'b') || (character[i] == 'c') || (character[i] == 'd') || (character[i] == 'e') || (character[i] == 'f')){
				res = (character[i] - 'W') * (1 / pow(16,i)) + res;
			}else{
				res = (character[i] - '0') * (1 / pow(16,i)) + res;
			}
		}
	}
    return res;
}

double binRealHandle(char *str){
	double res;
	int i;
	int length_str, length_decimal, length_real;
	char *character;
	length_str = strlen(str);
	character = strchr(str, '.');
	length_real = strlen(character) - 1;
	length_decimal = length_str - length_real + 1;
    
	res = (int)strtol(&str[2], &character, 2);
    
	for (i = 1; i <= length_real; i++){
		res = (character[i] - '0') * (1 / pow(2,i)) + res;
	}
	return res;
}

void yyerror(char *message){
	error_count++; 
	printf("(%d)ERROR: \"%s\" | TOKEN: %s | LINE: %d | ->%s<-\n",
	error_count, message, yytext, lineno, linestream);
	if(MAX_ERRORS == error_count){
 		printf("ERRORS DETECTED IN PROGRAM: %d\nERRORS ACCEPTED: %d\nTermination...\n", error_count, MAX_ERRORS); 
 		exit(-1);
	}
}

int main(int argc, char *argv[]){
	int token;
	
	++argv; --argc;
	if( argc > 0){
		yyin = fopen(argv[0], "r");
		if (yyin == NULL){
			perror ("Error opening file"); return -1;
		}
		yyin1 = fopen(argv[0], "r");
		if (yyin1 == NULL){
			perror ("Error opening file"); return -1;
		}
	}
	error_string();
	token = yylex();
	while(token != T_EOF){
		token = yylex();
	}
	fclose(yyin);
	yyterminate();
}

void error_string(void){
	off_t where;
	int k;
	char c;
	
	for(k = 0; k < MAX_LINE_SIZE; k++){
		linestream[k] = '\0';
	}
	
	k = 0;
	
	while(1){
		c = fgetc(yyin1);
		if( feof(yyin1) || c == '\n' ){ 
			break;
		}
		linestream[k] = c;
		k++;
	}
	if (feof(yyin1)){
		flag = 0;
	}
}
